config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  get '/tasks/descendant', to: 'tasks#descendant'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relational.rb
class Relational < ApplicationRecord
  belongs_to :parent, class_name: 'Task', foreign_key: :parent_id
  belongs_to :children, class_name: 'Task', foreign_key: :children_id, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  default_scope -> { order("tasks.id") }

  belongs_to :user

  has_many :parent_relationals, class_name: 'Relational', foreign_key: :parent_id
  has_many :children_relationals, class_name: 'Relational', foreign_key: :children_id, dependent: :destroy
  has_many :parent_task, through: :children_relationals, source: :parent
  has_many :children_tasks, through: :parent_relationals, source: :children, dependent: :destroy

  validates :title, presence: true

  def self.descendant_tasks(uid)
    descendant_ids = Array.new
    mytasks = Task.where(user_id: uid)
    mytasks.each do |task|
      unless task.children_tasks.any?
        descendant_ids << task.id
      end
    end
    return descendant_ids
  end

  # 自分も含めた親子関係を配列で返すメソッド
  def clans_to_me
    clan = Array.new
    task = self
    clan.unshift(task.id)
    while true
      if task.parent_task.first.nil?
        break
      else
        clan.unshift(task.parent_task.ids.first)
        task = Task.find(clan.first)
      end
    end
    return clan
  end

  # 自分の親までの親子関係を配列で返すメソッド
  def clans
    clan = Array.new
    task = self
    while true
      if task.parent_task.first.nil?
        break
      else
        clan.unshift(task.parent_task.ids.first)
        task = Task.find(clan.first)
      end
    end
    return clan
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :login_confirm

  def index
    @children_tasks = Task.where(level: 1, user_id: current_user.id)
  end

  def descendant
    @descendant_ids = Task.descendant_tasks(current_user.id)
  end

  def new
    if @task ||= Task.find_by(id: params[:format].to_i)
      @task.save
    end
    @relational = Relational.new
    @new_task = Task.new
  end

  def create
    @new_task = Task.new(task_params)
    @new_task.user_id = current_user.id
    if @new_task.save
      if @new_task.level == 1
        redirect_to tasks_path, notice: "タスクを作成しました"
      else
        @relational = Relational.new(params.require(:relational).permit(:parent_id).merge(children_id: @new_task.id))
        @relational.save
        redirect_to controller: :tasks, action: :show, id: @new_task.parent_task.ids.first, notice: "タスクを作成しました"
      end
    else
      render :new
    end
  end

  def show
    @children_tasks = @task.children_tasks
  end

  def edit
    @new_task = @task
  end

  def update
    if @task.update(task_params)
      unless @task.level == 1
        redirect_to task_path(@task.parent_task.first), notice: "タスクを編集しました"
      else
        redirect_to tasks_path, notice: "タスクを編集しました"
      end
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました"
  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :level, :done)
  end

  def relational_params
    params.require(:relational).permit(:parent_id)
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def login_confirm
    unless user_signed_in? then
      redirect_to new_user_session_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScriptYourself</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <ul>
      <% if user_signed_in? %>
      <li><strong><%= link_to current_user.email, edit_user_registration_path %></strong></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </ul>
  </header>
  <div class = "wrapper row">
    <aside class="side_menu col-xs-2">
      <nav>
        <ul>
          <li><%= link_to 'タスク確認', tasks_descendant_path %></li>
          <li><%= link_to '新規作成', new_task_path %></li>
          <li><%= link_to 'タスクツリー', tasks_path %></li>
        </ul>
      </nav>
    </aside>
    <article class="container col-xs-10">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </article>
  </div>
</body>
<footer class="footer">
  <p>hogehoge</p>
  <p>© 2018 Copyright oreore</p>
</footer>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @new_task, local: true) do |f| %>
<% if @new_task.errors.any? %>
  <div id="error_explanation">
    <h3><%= @new_task.errors.count %>件のエラーがあります。</h3>
    <ul>
      <% @new_task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="formArea">
  <table>
    <tr class="taskTitle">
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title, class: "titleField" %></td>
    </tr>
    <tr class="taskContent">
      <td><%= f.label :content %></td>
      <td><%= f.text_area :content, size: "50x5" %></td>
    </tr>
  </table>
  <div class="buttonArea">
    <% if controller.action_name == "new" %>
      <% if @task.nil? %>
        <% tmp = 1 %>
        <% parentId = 1 %>
      <% else %>
        <% tmp = @task.level.to_i + 1 %>
        <% parentId = @task.id %>
      <% end %>
      <%= fields_for(@relational) do |r| %>
        <%= r.hidden_field :parent_id, value: parentId %>
      <% end %>
      <%= f.hidden_field :level, value: tmp %>
    <% end %>
    <%= f.submit "保存" %>
  <% end %>
  </div>
</div>

app/views/tasks/_list.html.erb
<div class="">
  <% if @task != nil %>
    <p class="navigator">
      <% ids = @task.clans_to_me %>
      <%= render 'navigator', ids: ids %>
    </p>
  <% end %>
  <% @children_tasks.each do |task| %>
    <%= render 'taskpanel', task: task %>
  <% end %>
</div>

app/views/tasks/_navigator.html.erb
<% ids.each do |id| %>
  <% nav_task = Task.find(id) %>
  <% link_text = nav_task.title %>
  <% if link_id = nav_task.parent_task.ids.first != nil %>
    <% link_id = nav_task.parent_task.ids.first.to_i %>
    <% link = Task.find(link_id) %>
    <%= link_to link_text , task_path(link) %>
  <% else %>
    <%= link_to link_text , tasks_path %>
  <% end %>
  <%= " > " %>
<% end %>

app/views/tasks/_task_info.html.erb
<div class="row info-panel">
  <div class="contents col-xs-8">
    <p>Task_id:<%= task.id %></p>
    <p>Task_level:<%= task.level %></p>
    <p>Task_title:<%= task.title %></p>
    <p>Task_content:<%= task.content %></p>
  </div>
  <div class="links col-xs-4">
    <%= link_to '詳細', task, class:'btn btn-default' %>
    <%= link_to '下位タスク作成', new_task_path(task), class:'btn btn-default' %>
    <%= link_to '編集', edit_task_path(task), class:'btn btn-info' %>
    <%= link_to '削除', task, method: :delete, data:{confirm:'Are you sure?'}, class:'btn btn-danger' %>
  </div>
</div>

app/views/tasks/_taskpanel.html.erb
<div class="row taskPanel">
  <div class="contents col-xs-7">
    <p class="taskTitle"><strong><%= task.title %></strong></p>
    <p class="taskContent"><%= task.content %></p>
  </div>
  <div class="links col-xs-4">
    <%= link_to '下位タスク確認', task, class:'btn btn-default' %>
    <%= link_to '下位タスク作成', new_task_path(task), class:'btn btn-default' %>
    <%= link_to '編集', edit_task_path(task), class:'btn btn-info' %>
    <%= link_to '削除', task, method: :delete, data:{confirm:'本当に削除しますか?'}, class:'btn btn-danger' %>
  </div>
  <div class="completed col-xs-1">
    <%= form_with(model: task, local: true) do |f| %>
      <% if task.done == true %>
        <%= f.hidden_field :done, value: false %>
        <%= button_tag "完了取消", type: 'submit', class:'btn btn-default glyphicon glyphicon-remove' %>
      <% else %>
        <%= f.hidden_field :done, value: true %>
        <%= button_tag "完了する", type: 'submit', class:'btn btn-default glyphicon glyphicon-ok' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/descendant.html.erb
<h1>最小単位タスク</h1>
<%= link_to 'TOP', tasks_path %>
<div class="taskDescendant">
  <% @descendant_ids.each do |id| %>
    <% task = Task.find(id) %>
    <p class="navigatorDescendant">
      <% if task.level != 1 %>
        <% ids = task.clans %>
        <%= render 'navigator', ids: ids %>
      <% else %>
        <%= " > " %>
      <% end %>
    </p>
    <%= render 'taskpanel', task: task %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1>編集</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<%= link_to 'New', new_task_path %>
<%= render 'list' %>

app/views/tasks/new.html.erb
<h1>新規タスク作成</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %>の子要素一覧</h1>
<%= link_to 'TOP', tasks_path %>
<% if @task.level == 1 %>
  <%= link_to '上へ', tasks_path %>
<% else %>
  <% parentTask = @task.parent_task.ids.first %>
  <%= link_to '上へ', controller: :tasks, action: :show, id: parentTask %>
<% end %>
<%= link_to 'この階層に新規タスク作成', new_task_path(@task) %>
<%= render 'list' %>

app/views/welcome/index.html.erb
<section class="main-header">
  <div>
    <h1>卒業課題アプリケーション</h1>
  </div>
</section>
<section class="about">
  <h1>タスク細分化法によるタスク管理アプリ</h1>
  <h2>Task scripter</h2>
  <div class="link-buttons">
    <% if user_signed_in? %>
      <%= link_to 'タスク一覧', tasks_path %>
    <% else %>
      <%= link_to 'LOGIN', new_user_session_path, class:'btn btn-default btn-lg' %>
      <%= link_to 'SIGNUP', new_user_registration_path, class:'btn btn-primary btn-lg' %>
    <% end %>
  </div>
  <p>
    (説明)
  </p>
</section>